// scripts/blocks.js

const productionBlocks = [
    {
        id: 'graphite-press',
        name: 'Graphite Press',
        sprite: 'assets/sprites/graphite-press.png',
        description: 'Smelts Coal into Graphite.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        itemOutput: 2,
        input_rate: { coal: 3 },
        output_resource: 'graphite',
        cost: { copper: 75, lead: 30 },
        cost_multiplier: 1.5,
        consumption: 0,
        unlockReq: { upgradeId: "auto-sand", minLevel: 10 },
    },
    {
        id: 'multi-press',
        name: 'Multi Press',
        sprite: 'assets/sprites/multi-press.png',
        description: 'Smelts Coal into Graphite.',
        category: 'production',
        level: 0, maxLevel: 20, unlocked: false,
        craftSpeed: 5,
        input_rate: { coal: 4 },
        fluid_input_resource: 'water',
        fluid_input_rate: 6,
        output_resource: 'graphite',
        itemOutput: 4,
        cost: { graphite: 50, lead: 100, titanium: 100, silicon: 50 },
        cost_multiplier: 1.5,
        consumption: 0,
        unlockReq: { blockId: 'graphite-press', minLevel: 15 },
    },
    {
        id: 'silicon-smelter',
        name: 'Silicon Smelter',
        sprite: 'assets/sprites/silicon-smelter.png',
        description: 'Smelts Sand and Coal into Silicon.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        itemOutput: 2,
        input_rate: { sand: 4, coal: 2 },
        output_resource: 'silicon',
        cost: { copper: 300, lead: 200, graphite: 50 },
        cost_multiplier: 1.5,
        consumption: 10,
        unlockReq: { resource: 'sand', minAmount: 1000 },
    },
    {
        id: 'silicon-crucible',
        name: 'Silicon Crucible',
        sprite: 'assets/sprites/silicon-crucible.png',
        description: 'Refines silicon from sand and coal, using pyratite as an additional heat source.',
        category: 'production',
        level: 0, maxLevel: 20, unlocked: false,
        craftSpeed: 2,
        input_rate: { sand: 4, coal: 2, pyratite: 1 },
        output_resource: 'silicon',
        itemOutput: 4,
        cost: { copper: 300, lead: 200, graphite: 50 },
        cost_multiplier: 1.5,
        consumption: 10,
        unlockReq: { blockId: 'silicon-smelter', minLevel: 15 },
    },
    {
        id: 'kiln',
        name: 'Kiln',
        sprite: 'assets/sprites/kiln.png',
        description: 'Smelts Sand and Lead into Metaglass.',
        category: 'production',
        level: 0, maxLevel: 20, unlocked: false,
        craftSpeed: 1,
        input_rate: { sand: 2, lead: 2 },
        output_resource: 'metaglass',
        itemOutput: 2,
        cost: { copper: 60, lead: 30 },
        cost_multiplier: 1.5,
        consumption: 20,
        unlockReq: { blockId: 'silicon-smelter', minLevel: 3 },
    },
    {
        id: 'coal-centrifuge',
        name: 'Coal Centrifuge',
        sprite: 'assets/sprites/coal-centrifuge.png',
        description: 'Transform Oil into Coal.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        fluid_input_resource: 'oil',
        fluid_input_rate: 8,
        output_resource: 'coal',
        itemOutput: 2,
        cost: { lead: 15, graphite: 20, titanium: 10 },
        cost_multiplier: 1.5,
        consumption: 15,
        unlockReq: { blockId: 'oil-extractor', minLevel: 1 },
    },
    {
        id: 'plastanium-compressor',
        name: 'Plastanium Compressor',
        sprite: 'assets/sprites/plastanium-compressor.png',
        description: 'Compresses Titanium, Coal and Oil into Plastanium.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        input_rate: { titanium: 2, coal: 2 },
        fluid_input_resource: 'oil',
        fluid_input_rate: 15,
        output_resource: 'plastanium',
        itemOutput: 2,
        cost: { titanium: 80, copper: 60, lead: 40, silicon: 30 },
        cost_multiplier: 1.5,
        consumption: 60,
        unlockReq: { blockId: 'spore-press', minLevel: 5 },
    },
    {
        id: 'phase-weaver',
        name: 'Phase Weaver',
        sprite: 'assets/sprites/phase-weaver.png',
        description: 'Weaves Thorium and Sand into Phase Fabric.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        input_rate: { thorium: 4, sand: 10 },
        output_resource: 'phase-fabric',
        itemOutput: 2,
        cost: { titanium: 100, silicon: 80, lead: 50 },
        cost_multiplier: 1.5,
        consumption: 100,
        unlockReq: { blockId: 'plastanium-compressor', minLevel: 3 },
    },
    {
        id: 'surge-smelter',
        name: 'Surge Smelter',
        sprite: 'assets/sprites/surge-smelter.png',
        description: 'Alloys Copper, Lead, Titanium and Silicon into Surge Alloy.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        input_rate: { copper: 2, lead: 2, titanium: 1, silicon: 1 },
        output_resource: 'surge-alloy',
        cost: { copper: 200, lead: 180, titanium: 70, silicon: 60 },
        cost_multiplier: 1.5,
        consumption: 120,
        unlockReq: { blockId: 'phase-weaver', minLevel: 1 },
    },
    {
        id: 'separator',
        name: 'Separator',
        sprite: 'assets/sprites/separator.png',
        description: 'Separates Slag into Copper, Lead, Graphite and Titanium.',
        category: 'production',
        level: 0, maxLevel: 15, unlocked: false,
        fluid_input_resource: 'slag',
        fluid_input_rate: 25,
        output_resources: { copper: 5, lead: 5, graphite: 3, titanium: 4 },
        cost: { copper: 50, titanium: 40, graphite: 30 },
        cost_multiplier: 1.6,
        consumption: 20,
        unlockReq: { blockId: 'slag-extractor', minLevel: 1 },
    },
    {
        id: 'interplanetary-accelerator',
        name: 'Interplanetary Accelerator',
        sprite: 'assets/sprites/interplanetary-accelerator.png',
        description: 'The ultimate endgame construct to leave this planet. All Items Multiplier x20',
        category: 'production',
        level: 0, maxLevel: 1, unlocked: false,
        cost: {
            copper: 1000000, lead: 1000000, sand: 2000000, coal: 2000000,
            titanium: 600000, thorium: 600000, graphite: 100000, metaglass: 100000,
            silicon: 50000, plastanium: 50000, 'phase-fabric': 50000,
            'surge-alloy': 50000, 'spore-pod': 50000, pyratite: 50000, 'blast-compound': 50000,
        },
        cost_multiplier: 1,
        consumption: 100000,
        unlockReq: { blockId: 'surge-smelter', minLevel: 15 },
    },
];

const energyBlocks = [
    {
        id: 'battery',
        name: 'Battery',
        sprite: 'assets/sprites/battery.png',
        description: 'Increases energy storage by +200 per level.',
        category: 'energy',
        level: 0, maxLevel: 15, unlocked: false,
        storage_per_level: 200,
        cost: { copper: 50, lead: 20 },
        cost_multiplier: 1.5,
        unlockReq: { resource: 'lead', minAmount: 200 },
    },
    {
        id: 'large-battery',
        name: 'Large Battery',
        sprite: 'assets/sprites/battery-large.png',
        description: 'Increases energy storage by +1,000 per level.',
        category: 'energy',
        level: 0, maxLevel: 20, unlocked: false,
        storage_per_level: 1000,
        cost: { lead: 100, silicon: 50, titanium: 20 },
        cost_multiplier: 1.6,
        unlockReq: { blockId: 'battery', minLevel: 10 },
    },
    {
        id: 'combustion-generator',
        name: 'Combustion Generator',
        sprite: 'assets/sprites/combustion-generator.png',
        description: 'Burns Coal to generate 15 E/s per level.',
        category: 'energy',
        level: 0, maxLevel: 25, unlocked: false,
        output_per_level: 15,
        input_resource: 'coal',
        input_per_level: 1,
        cost: { copper: 300, lead: 200, graphite: 50 },
        cost_multiplier: 1.5,
        unlockReq: { blockId: 'battery', minLevel: 1 },
    },
    {
        id: 'steam-generator',
        name: 'Steam Generator',
        sprite: 'assets/sprites/steam-generator.png',
        description: 'Burns Coal and uses Water to generate a large amount of energy.',
        category: 'energy',
        level: 0, maxLevel: 15, unlocked: false,
        output_per_level: 55,
        input_resource: 'coal',
        input_per_level: 2,
        fluid_input_resource: 'water',
        fluid_input_rate: 10,
        cost: { copper: 35, graphite: 40 },
        cost_multiplier: 1.6,
        unlockReq: { blockId: 'water-extractor', minLevel: 1 },
    },
    {
        id: 'rtg-generator',
        name: 'RTG Generator',
        sprite: 'assets/sprites/rtg-generator.png',
        description: 'Slowly decays Thorium for stable 70 E/s per level.',
        category: 'energy',
        level: 0, maxLevel: 10, unlocked: false,
        output_per_level: 70,
        input_resource: 'thorium',
        input_per_level: 2,
        cost: { lead: 100, copper: 50, thorium: 30 },
        cost_multiplier: 1.5,
        unlockReq: { resource: 'thorium', minAmount: 100 },
    },
    {
        id: 'differential-generator',
        name: 'Differential Generator',
        sprite: 'assets/sprites/differential-generator.png',
        description: 'Utilizes the temperature difference between Cryofluid and burning Pyratite for high efficiency energy generation.',
        category: 'energy',
        level: 0, maxLevel: 10, unlocked: false,
        output_per_level: 400,
        input_resource: 'pyratite',
        input_per_level: 2,
        fluid_input_resource: 'cryo',
        fluid_input_rate: 10,
        cost: { copper: 70, lead: 50, titanium: 50, silicon: 50 },
        cost_multiplier: 1.7,
        unlockReq: { blockId: 'pyratite-mixer', minLevel: 1 },
    },
    {
        id: 'thorium-reactor',
        name: 'Thorium Reactor',
        sprite: 'assets/sprites/thorium-reactor.png',
        description: 'Fissions Thorium safely with Cryofluid to generate 810 E/s per level.',
        category: 'energy',
        level: 0, maxLevel: 15, unlocked: false,
        output_per_level: 810,
        input_resources: { 'thorium': 5 },
        fluid_input_resource: 'cryo',
        fluid_input_rate: 30,
        cost: { lead: 300, silicon: 200, graphite: 150, thorium: 150 },
        cost_multiplier: 1.8,
        unlockReq: { blockId: 'cryofluid-mixer', minLevel: 1 },
    },
    {
        id: 'impact-reactor',
        name: 'Impact Reactor',
        sprite: 'assets/sprites/impact-reactor.png',
        description: 'Consumes Blast Compound for 2550 E/s per level.',
        category: 'energy',
        level: 0, maxLevel: 5, unlocked: false,
        output_per_level: 2550,
        input_resources: { 'blast-compound': 10 },
        cost: { copper: 1000, lead: 1000, silicon: 300, 'surge-alloy': 250, thorium: 200 },
        cost_multiplier: 2.0,
        unlockReq: { blockId: 'thorium-reactor', minLevel: 5 },
    },
];

const liquidBlocks = [
    {
        id: 'liquid-tank',
        name: 'Liquid Tank',
        sprite: 'assets/sprites/liquid-tank.png',
        description: 'Adds +1,000 capacity to all liquids.',
        category: 'liquids',
        level: 0, maxLevel: 25, unlocked: false,
        storage_per_level: 1000,
        cost: { titanium: 40, metaglass: 30 },
        cost_multiplier: 1.5,
        consumption: 0,
        unlockReq: { itemId: 'metaglass', minAmount: 200 },
    },
    {
        id: 'water-extractor',
        name: 'Water Extractor',
        sprite: 'assets/sprites/water-extractor.png',
        description: 'Extracts groundwater.',
        category: 'liquids',
        level: 0, maxLevel: 15, unlocked: false,
        fluid_output_resource: 'water',
        fluid_output_rate: 30,
        cost: { copper: 30, lead: 30, graphite: 15, metaglass: 20 },
        cost_multiplier: 1.5,
        consumption: 5,
        unlockReq: { blockId: 'graphite-press', minLevel: 3 },
    },
    {
        id: 'water-pump',
        name: 'Water Pump',
        sprite: 'assets/sprites/rotary-pump.png',
        description: 'Extracts water.',
        category: 'liquids',
        level: 0, maxLevel: 20, unlocked: false,
        fluid_output_resource: 'water',
        fluid_output_rate: 50,
        cost: { copper: 70, silicon: 20, graphite: 35, metaglass: 50 },
        cost_multiplier: 1.5,
        consumption: 10,
        unlockReq: { blockId: 'water-extractor', minLevel: 15 },
    },
    {
        id: 'slag-extractor',
        name: 'Slag Extractor',
        sprite: 'assets/sprites/mechanical-pump-slag.png',
        description: 'Extracts molten slag from the core.',
        category: 'liquids',
        level: 0, maxLevel: 15, unlocked: false,
        fluid_output_resource: 'slag',
        fluid_output_rate: 40,
        cost: { metaglass: 50, graphite: 40, titanium: 20 },
        cost_multiplier: 1.6,
        consumption: 30,
        unlockReq: { blockId: 'water-extractor', minLevel: 5 },
    },
    {
        id: 'cultivator',
        name: 'Cultivator',
        sprite: 'assets/sprites/cultivator.png',
        description: 'Grows Spore Pods using Water.',
        category: 'liquids',
        level: 0, maxLevel: 20, unlocked: false,
        craftSpeed: 1,
        input_rate: {},
        itemOutput: 4,
        fluid_input_resource: 'water',
        fluid_input_rate: 10,
        output_resource: 'spore-pod',
        cost: { copper: 20, lead: 20, silicon: 10 },
        cost_multiplier: 1.5,
        consumption: 10,
        unlockReq: { blockId: 'water-extractor', minLevel: 1 },
    },
    {
        id: 'oil-extractor',
        name: 'Oil Extractor',
        sprite: 'assets/sprites/oil-extractor.png',
        description: 'Extracts Oil from the ground.',
        category: 'liquids',
        level: 0, maxLevel: 15, unlocked: false,
        input_rate: { sand: 1 },
        fluid_input_resource: 'water',
        fluid_input_rate: 5,
        fluid_output_resource: 'oil',
        fluid_output_rate: 15,
        cost: { copper: 80, lead: 50, graphite: 100, silicon: 15, thorium: 50 },
        cost_multiplier: 1.5,
        consumption: 50,
        unlockReq: { blockId: 'water-extractor', minLevel: 1 },
    },
    {
        id: 'spore-press',
        name: 'Spore Press',
        sprite: 'assets/sprites/spore-press.png',
        description: 'Squishes Spore Pods into Oil.',
        category: 'liquids',
        level: 0, maxLevel: 20, unlocked: false,
        input_rate: { 'spore-pod': 2 },
        fluid_output_resource: 'oil',
        fluid_output_rate: 20,
        cost: { copper: 60, lead: 40, silicon: 20 },
        cost_multiplier: 1.5,
        consumption: 25,
        unlockReq: { blockId: 'cultivator', minLevel: 3 },
    },
    {
        id: 'cryofluid-mixer',
        name: 'Cryofluid Mixer',
        sprite: 'assets/sprites/cryofluid-mixer.png',
        description: 'Mixes Water and Titanium into Cryofluid.',
        category: 'liquids',
        level: 0, maxLevel: 15, unlocked: false,
        input_rate: { titanium: 5 },
        fluid_input_resource: 'water',
        fluid_input_rate: 35,
        fluid_output_resource: 'cryo',
        fluid_output_rate: 30,
        cost: { silicon: 60, lead: 40, titanium: 30 },
        cost_multiplier: 1.5,
        consumption: 25,
        unlockReq: { blockId: 'water-extractor', minLevel: 5 },
    },
    {
        id: 'pyratite-mixer',
        name: 'Pyratite Mixer',
        sprite: 'assets/sprites/pyratite-mixer.png',
        description: 'Mixes Coal, Lead and Sand into Pyratite.',
        category: 'liquids',
        level: 0, maxLevel: 20, unlocked: false,
        craftSpeed: 1,
        input_rate: { coal: 2, lead: 1, sand: 1 },
        output_resource: 'pyratite',
        itemOutput: 3,
        cost: { copper: 50, lead: 40, graphite: 36 },
        cost_multiplier: 1.5,
        consumption: 10,
        unlockReq: { blockId: 'kiln', minLevel: 5 },
    },
    {
        id: 'blast-mixer',
        name: 'Blast Mixer',
        sprite: 'assets/sprites/blast-mixer.png',
        description: 'Combines Pyratite and Spore Pods into Blast Compound.',
        category: 'liquids',
        level: 0, maxLevel: 15, unlocked: false,
        craftSpeed: 1,
        input_rate: { pyratite: 2, 'spore-pod': 1 },
        output_resource: 'blast-compound',
        itemOutput: 2,
        cost: { silicon: 60, lead: 40, titanium: 30 },
        cost_multiplier: 1.5,
        consumption: 15,
        unlockReq: { blockId: 'pyratite-mixer', minLevel: 5 },
    },
];

const logicBlocks = [
    {
        id: 'micro-processor',
        name: 'Logic Processor',
        sprite: 'assets/sprites/message.png',
        description: 'Enables quick +/- level controls for all factory blocks.',
        category: 'logic',
        level: 0, maxLevel: 1, unlocked: false,
        cost: { copper: 2000, lead: 2000, graphite: 500, silicon: 300 },
        cost_multiplier: 1,
        unlockReq: { blockId: 'silicon-smelter', minLevel: 10 },
    },
    {
        id: 'mono',
        name: 'Mono',
        sprite: 'assets/sprites/mono.png',
        description: 'Automatically mines 2/s Copper and Lead. Grants a stacking 1.3x global mining multiplier.',
        category: 'logic',
        level: 0, maxLevel: 15, unlocked: false,
        mining_rate: 2,
        bonus_multiplier: 1.3,
        cost: { silicon: 300, lead: 200 },
        cost_multiplier: 1.5,
        consumption: 10,
        unlockReqs: [
            { upgradeId: 'auto-copper', minLevel: 20 },
            { upgradeId: 'auto-lead', minLevel: 20 }
        ],
    },
    {
        id: 'mass-driver',
        name: 'Mass Driver',
        sprite: 'assets/sprites/mass-driver.png',
        description: 'Global 1.5x production multiplier for factories with 2+ inputs.',
        category: 'logic',
        level: 0, maxLevel: 5, unlocked: false,
        cost: { silicon: 5000, 'phase-fabric': 1000, 'surge-alloy': 500 },
        cost_multiplier: 2.5,
        unlockReq: { blockId: 'surge-smelter', minLevel: 5 },
    },
];
